id: P000103
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །ཐུན་མིན་སྔོན་འགྲོའི་ཁྲིད་ཡིག་སྙིང་པོ་ཀུན་དྲིལ་མ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། མཚུངས་མེད་གྲུབ་པའི་དབང་ཕྱུག་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྒྱལ་སྲས་འཕགས་མཆོག་རྡོ་རྗེ་མཆོག
  layers:
  - book_title
  - author
  - quotation
  - sabche
  id: KS-SP-02
web_metadata:
  title:
    en: The All Encompassing Quintessence:An Instruction on the Uncommon Preliminary
      Practices
    bo: ཐུན་མིན་སྔོན་འགྲོའི་ཁྲིད་ཡིག་སྙིང་པོ་ཀུན་དྲིལ་མ་བཞུགས་སོ།།
  collection:
    en: Se Phakchok Series–  Book 2
    bo: སྲས་འཕགས་མཆོག།–  དེབ། ༢
  author:
    en: Authors:Phakchok Dorje
    bo: འཕགས་མཆོག་རྡོ་རྗེ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-SP-02
  category:
    en: Preliminary Practices
    bo: སྔོན་འགྲོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-SP-02.epub
  description:
    en: ''
    bo: ''
